name: 'Rembrandt'
version: 0.0.1
description: project about great painter

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  test: ^0.12.15+1
  grinder: ^0.8.0
  yaml: ^2.1.8
  archive: ^1.0.20
  path: ^1.3.9
  mime: ^0.9.3
  intl: ^0.13.0
  html5lib: any
  xml: ^2.4.0

dev_dependencies:
  barback: 0.15.2